### ISSUE TITLE
[Bug] 在 QQNT 9.9.2-16736 下 Chronocat 启动后 qq闪退重启

### ISSUE THREAD

**Issue by RF-Tar-Railt** [chrononeko/bugtracker#11]
使用的是 liteloader的 chronocat插件
版本 0.0.40

**Comment by ilharp** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/147

LiteLoaderQQNT 当前最高完美支持的版本是 16183。Chronocat 由插件框架加载，因此无法处理 QQ 无法稳定运行引起的相关问题，请谅解。
