### ISSUE TITLE
获取群成员列表时只能获取到index

### ISSUE THREAD

**Issue by Cola-Ace** [chrononeko/bugtracker#12]
https://github.com/chrononeko/chronocat/blob/master/packages/core/src/routes/group/getMemberList.ts
按照源码来看，最终返回的值应该包含用户的uid，index和detail，但我不管通过POST还是WebSocket都只能获取到index的值，甚至响应中不存在uid和detail这两个键
环境：
LiteLoaderQQNT: 0.5.3
Chronocat: 0.0.41
系统：Ubuntu 22.04
QQ: 3.1.2-13107

**Comment by ilharp** [comment]
![image](https://github.com/chrononeko/bugtracker/assets/20179549/44b47f28-b04d-499b-b597-40d8d80e53d6)

使用相同的 0.0.41 版本在 Windows 下工作正常。可否提供下使用 HTTP 的响应内容？

**Comment by Cola-Ace** [comment]
![QQ截图20230916231602](https://github.com/chrononeko/bugtracker/assets/73228853/224d0d20-232d-4c97-a4ae-e71a61693325)

**Comment by Cola-Ace** [comment]
我推测可能是ubuntu版的QQ版本太低导致的信息获取不到，但更新到最新版本后QQ会闪退，所以目前我也没有头绪

**Comment by ilharp** [comment]
请尝试使用更新的 QQ 客户端。
