### ISSUE TITLE
功能请求：希望增加获取qq消息内图片的功能

### ISSUE THREAD

**Issue by Cola-Ace** [chrononeko/bugtracker#13]
似乎cbronocat并没有这个功能（只有上传功能），如果需要对图片进行操作的话需要自己另写功能

**Comment by ilharp** [comment]
WebSocket 会推送消息内附带的媒体信息，API `fetchRichMedia` 可以使用这些信息下载所需媒体。图片、语音、视频和文件等均可从此 API 获取。请问是哪一部分遇到了问题呢？

**Comment by Cola-Ace** [comment]
之前没注意到有这么一个api，很抱歉浪费了你的时间
