### ISSUE TITLE
Bug:getMemberList返回问题

### ISSUE THREAD

**Issue by Lilyltt** [chrononeko/bugtracker#20]
getMemberList在get的时候 如果不在ui中选中目标群 就会返回空集合,其次 如果没有手动滑动群列表 加载完所有群员 就只会返回一部分信息(30个) Version:0.0.45

**Comment by Lilyltt** [comment]
补充,qq版本为9.9.2-16183 (64位)

**Comment by ikechan8370** [comment]
我还遇到了只拿到2个群成员的情况。

**Comment by ilharp** [comment]
v0.0.68 已修复。
