### ISSUE TITLE
生成的配置文件在哪

### ISSUE THREAD

**Issue by baclt1580** [chrononeko/bugtracker#21]
文档上写的是在用户目录下,但没有

**Comment by ilharp** [comment]
Chronocat 配置是版本 0.0.46 的新增功能，将会在几天后发版。有需要的话可以先使用 [这里](https://github.com/chrononeko/chronocat/actions/runs/6288305810) 的 [开发构建](https://chronocat.vercel.app/more/use-dev-build) 尝试。

**Comment by baclt1580** [comment]
> Chronocat 配置是版本 0.0.46 的新增功能，将会在几天后发版。有需要的话可以先使用 [这里](https://github.com/chrononeko/chronocat/actions/runs/6288305810) 的 [开发构建](https://chronocat.vercel.app/more/use-dev-build) 尝试。

请问现在是不是会自动生成token,我远程连接red服务提示unauthorized

**Comment by ilharp** [comment]
> 请问现在是不是会自动生成token,我远程连接red服务提示unauthorized

是的，这是版本 0.0.1 功能。

**Comment by baclt1580** [comment]
> > 请问现在是不是会自动生成token,我远程连接red服务提示unauthorized
> 
> 是的，这是版本 0.0.1 功能。

有办法看token是多少吗,我用的liteloader插件

**Comment by ilharp** [comment]
> 有办法看token是多少吗,我用的liteloader插件

你所使用的框架文档上一般会给出 token 的所在位置。你所使用的框架文档上没有说明吗？

**Comment by baclt1580** [comment]
> > 有办法看token是多少吗,我用的liteloader插件
> 
> 你所使用的框架文档上一般会给出 token 的所在位置。你所使用的框架文档上没有说明吗？

没看到有这方面的说明,如果我用0.0.46是不是可以通过配置文件自定义token

**Comment by ilharp** [comment]
> 没看到有这方面的说明,如果我用0.0.46是不是可以通过配置文件自定义token

如果你直接使用 red 协议，那么 [这里](https://chrononeko.github.io/QQNTRedProtocol) 有说明。如果你使用 0.0.46，那么你可以直接通过修改 `chronocat.yml` 来自定义 token。

**Comment by baclt1580** [comment]
> > 没看到有这方面的说明,如果我用0.0.46是不是可以通过配置文件自定义token
> 
> 如果你直接使用 red 协议，那么 [这里](https://chrononeko.github.io/QQNTRedProtocol) 有说明。如果你使用 0.0.46，那么你可以直接通过修改 `chronocat.yml` 来自定义 token。

好的,问题已经解决了,非常感谢
