### ISSUE TITLE
Bug(Koishi adapter): Unable to send the rendered images when using the <html> element.

### ISSUE THREAD

**Issue by Lipraty** [chrononeko/bugtracker#29]
### Description

Unable to send the rendered images when using the <html> element (supported by puppeteer service), and there no error messages in the console.

### Screenshots

it works in:
![22baada94588553aabcef82c9c277314](https://github.com/chrononeko/bugtracker/assets/18106422/86de8720-2265-4985-a22e-abbec2de4d20)
![image](https://github.com/chrononeko/bugtracker/assets/18106422/11e69775-dd30-46d3-8c1e-f011aa19d043)

in `@chronocat/adapter`
![image](https://github.com/chrononeko/bugtracker/assets/18106422/2f332b15-aacd-448e-87f4-2087873bb423)

## Other

System:
    OS: Linux 6.2 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (64) x64 Genuine Intel(R) CPU

Binaries:
    Node: 19.8.1
    Yarn: 1.22.19

Koishi:
    Core: 4.14.6
    Console: 5.14.4

*Chroncat running in windows server 2021

**Comment by ilharp** [comment]
Chronocat 已经重构了获取资源的逻辑，麻烦看下此问题是否已解决。

**Comment by Lipraty** [comment]
fixed
