### ISSUE TITLE
[BUG] 无法访问消息中的图片链接

### ISSUE THREAD

**Issue by TheresaQWQ** [chrononeko/bugtracker#33]
日志如下
![ed68168e8ec2b63156ea079d92e36d7e](https://github.com/chrononeko/bugtracker/assets/22370654/44387e75-479d-420a-a81e-31036f311af5)

看起来是这一块的报错：

https://github.com/chrononeko/chronocat/blob/69eb7a8e7d6fa1766d9e3e14d6fff43a6462457f/packages/core/src/satori/routes/assets.ts#L15-L17

有一说一没看明白这是怎么报错的，顺便问一下开发环境怎么整呢？

**Comment by ilharp** [comment]
已修

开发环境的话……好像没有什么特别需要说明的，用 `yarn` 装好依赖以后直接 `yarn build`，项目下的 `build` 目录就会出现所有发布的东西，包括 LiteLoaderQQNT 的插件文件夹，把文件夹用 [离线安装](https://chronocat.vercel.app/install/llqqnt-airgap) 的方法扔进 LiteLoader 的插件目录就可以了

遇到什么问题直接找我问我就行（嗯
