### ISSUE TITLE
在nonebot下使用时发送消息失败

### ISSUE THREAD

**Issue by Viottery** [chrononeko/bugtracker#36]
nonebot相关配置：DRIVER=~httpx+~websockets

Chronocat相关配置：red

环境：Windows10， 使用推荐版本的QQ

问题描述：nonebot可以连接到Chronocat并正常接受消息事件。但每次尝试使用nonebot内置的/echo或是adapter-red给出的实例代码发送普通消息时恒报错：Networkerror。
![image](https://github.com/chrononeko/bugtracker/assets/52962187/a13f5bca-f26d-434e-95af-b402ae52a70f)

以前使用go-CQhttp主要编码内容都是写插件，处理这种项目的能力并不是很强，还望指点一二。

**Comment by ilharp** [comment]
Chrononeko Bugtracker 主要用于追踪 Chronocat 本身的问题。对于 [NoneBot-Adapter-Red](https://github.com/nonebot/adapter-red) 项目的问题，我推荐你前往 [NoneBot-Adapter-Red 的 Issue 区](https://github.com/nonebot/adapter-red/issues) 创建 Issue。

有其他问题的话可以在此 Issue 下继续留言。
