### ISSUE TITLE
feat: sendMsg return msgId

### ISSUE THREAD

**Issue by Hieuzest** [chrononeko/bugtracker#4]

**Comment by Hieuzest** [comment]
are your guys kiding on return sendMsg result？that does not make any sense.

I think we could compare message contents between sent mesaages and records from msgListInfo, but that would be dirty and may mismatch in several situations.

another solution might be directly match from sending timestamps and client sequences. Still there could be issues.

is it even possible to pass given args to reflect on msgList?

**Comment by MicroCBer** [comment]
> I think we could compare message contents between sent mesaages and records 
from msgListInfo, but that would be dirty...

I haven't checked the return value of sendMsg result, and that's why I didn't flag the commit as `close` the issue.

If there's not any useful result in sendMsg return value, there's a IPC send callback after sending the message that could be used.

**Comment by Hieuzest** [comment]
[d0c5bf24](https://github.com/koikirin/chronocat/commit/d0c5bf247a27d4cbedda780328765a859c224227)
i don't feel i should push this upstream though

**Comment by MicroCBer** [comment]
I don't think the callback you're using is the callback I mentioned before. I'm waiting for @ilharp 's debugger to take a look at it.

**Comment by MicroCBer** [comment]
is adding a dummy element really a good idea? note that it could be sent to the server and any malformed packet may probably seen as proof of using a bot framework. We should avoid this

**Comment by MicroCBer** [comment]
If there's no beautiful solution from cpp, I can also resolve it from the native side, but we'll need a `.node` native module which can be hard to maintain.

**Comment by MicroCBer** [comment]
However, I believe that there should be a way on the JS side to match the send success callback with the send message invocation, as the QQNT itself would display a loading icon beside the message until the message was successfully sent.

**Comment by MicroCBer** [comment]
Let's wait for the debugger first.

**Comment by Hieuzest** [comment]
> However, I believe that there should be a way on the JS side to match the send success callback with the send message invocation, as the QQNT itself would display a loading icon beside the message until the message was successfully sent.

Actually, it don't need to, since there do exist a list holding all pending messages and tracking status of each. NT client has nothing to do with the invovations but simply present these messages so there is no matching.

**Comment by MicroCBer** [comment]
> Actually, it don't need to, since there do exist a list holding all pending messages and tracking status of each. NT client has nothing to do with the invovations but simply present these messages so there is no matching.

Nah, have you seen the loading icon? How could it display a loading icon without matching it? Also if you send some ~~sexy images~~ or are disconnected from the network, how could display the small retry button beside the corresponding message if not matching it?

**Comment by MicroCBer** [comment]
oh, I see

**Comment by MicroCBer** [comment]
```
[ 🔗 ↑ ] CmdName: nodeIKernelMsgListener/onAddSendMsg Payload: {
  msgRecord: {
    msgId: '7272438935119848258',
    msgRandom: '1567328768',
    msgSeq: '285',
    cntSeq: '0',
    chatType: 2,
    msgType: 2,
    subMsgType: 1,
    sendType: 1,
    senderUid: 'u_OtJTqpFvVc3bA--L0ahAPA',
    peerUid: '892539614',
    channelId: '',
    guildId: '',
    guildCode: '0',
    fromUid: '0',
    fromAppid: '0',
    msgTime: '1693246638',
    msgMeta: '0x',
    sendStatus: 1,
    sendMemberName: '',
    sendNickName: '时空猫猫',
    guildName: '',
    channelName: '',
    elements: [ [Object] ],
    records: [],
    emojiLikesList: [],
    commentCnt: '0',
    directMsgFlag: 0,
    directMsgMembers: [],
    peerName: 'MicroBlock1、时空猫猫',
    freqLimitInfo: null,
    editable: true,
    avatarMeta: '',
    avatarPendant: '',
    feedId: '',
    roleId: '0',
    timeStamp: '0',
    clientIdentityInfo: null,
    isImportMsg: false,
    atType: 0,
    roleType: 0,
    fromChannelRoleInfo: { roleId: '0', name: '', color: 0 },
    fromGuildRoleInfo: { roleId: '0', name: '', color: 0 },
    levelRoleInfo: { roleId: '0', name: '', color: 0 },
    recallTime: '0',
    isOnlineMsg: false,
    generalFlags: '0x',
    clientSeq: '28763',
    fileGroupSize: null,
    foldingInfo: null,
    nameType: 0,
    avatarFlag: 0,
    anonymousExtInfo: null,
    personalMedal: null,
    roleManagementTag: null
  }
} Full: [
  'IPC_DOWN_2',
  { type: 'request', eventName: 'ns-ntApi-2' },
  [
    {
      cmdName: 'nodeIKernelMsgListener/onAddSendMsg',
      cmdType: 'event',
      payload: [Object]
    }
  ]
]
```

Here's a `clientSeq` field in this callback, and this can probably indicate the order of the messages that were sent if we are able to get the current clientSeq number.

**Comment by MicroCBer** [comment]
Okay, currently, as I observed, the `clientSeq` wouldn't change without sending a message. This would enable us to correspond the message object with the send request

**Comment by Hieuzest** [comment]
i can confirm this indicate the order, but i don't think ipc can preserve request order

**Comment by MicroCBer** [comment]
> i can confirm this indicate the order, but i don't think ipc can preserve request order

JS is single-threaded, which means it won't go any further before successfully invoking the IPC call. We could have a try at least.

**Comment by MicroCBer** [comment]
Note that it's different in different peers.

**Comment by Hieuzest** [comment]
i recognize that it is impossible to do a benchmark of sending really massive messages. Maybe i'm overthinking about it. the ipc is fast enough that it is totally afforable if we add some soft restriction like rate limit of 20 messages/s

**Comment by MicroCBer** [comment]
> i recognize that it is impossible to do a benchmark of sending really massive messages. Maybe i'm overthinking about it. the ipc is fast enough that it is totally afforable if we add some soft restriction like rate limit of 20 messages/s

the bottleneck of sending message is not at IPC, it's at network.

Even a rate limit of 2msg/s is totally acceptable for most situations
