### ISSUE TITLE
使用Chrononeko+adapter-red适配器发送语音时，PC客户端表现异常，安卓手机正常

### ISSUE THREAD

**Issue by qn8524king** [chrononeko/bugtracker#43]
https://github.com/nonebot/adapter-red/issues/21
这是adapter-red的issue

**使用的是wav格式的音频，测试过使用pydub+pilk转换为silk格式后问题仍然存在，只不过在电脑NTQQ上有一小部分可以正常播放而已**

发送语音至群聊内时：
NTQQ侧的表现为：
![image](https://github.com/chrononeko/bugtracker/assets/49012015/b3aac163-ca1c-4e72-9f05-495b03e94716)
语音显示正常，但点击提示："InitFromFile Fail"
普通PC侧QQ的表现为：
![7GA H~UNOE`M `OIOM{%FY](https://github.com/chrononeko/bugtracker/assets/49012015/a6324a86-dfe8-40d4-88eb-0ba1136842d3)
呈现一个图片的造型_(:з」∠)_也点不开
安卓QQ的表现为：
![image](https://github.com/chrononeko/bugtracker/assets/49012015/6917b904-46be-4d00-8b21-3b23bee6f95d)
语音显示正常，播放正常

发送语音至好友内，NTQQ侧的表现为：
![image](https://github.com/chrononeko/bugtracker/assets/49012015/b1d351e8-5606-4f6d-ad2f-9b82dcf95ad1)
语音显示正常，但点击提示："InitFromFile Fail"
普通PC侧QQ的表现为：
![image](https://github.com/chrononeko/bugtracker/assets/49012015/47b09c15-ce11-40ed-8e21-c05add187905)
语音显示正常，但点击后无任何反应，也没有声音
安卓QQ的表现为：
![image](https://github.com/chrononeko/bugtracker/assets/49012015/6917b904-46be-4d00-8b21-3b23bee6f95d)
语音显示正常，播放正常

silk格式的语音也一样会有显示上和播放上的问题，安卓手机上都是正常可播放的

**Comment by ilharp** [comment]
语音需要转换的格式为专属的 Silk 格式，并非通常意义上的 Silk，需要使用专属编码器编码。

后续 Chronocat 有计划内置语音编码器，但目前没有；你需要前往 [社区](https://chronocat.vercel.app/more/community) 寻找专属编码器。

**Comment by qn8524king** [comment]
> 语音需要转换的格式为专属的 Silk 格式，并非通常意义上的 Silk，需要使用专属编码器编码。
> 
> 后续 Chronocat 有计划内置语音编码器，但目前没有；你需要前往 [社区](https://chronocat.vercel.app/more/community) 寻找专属编码器。

好吧，我是调用的
pilk.encode(file_path_pcm, file_path_silk, pcm_rate=origin_media.frame_rate, tencent=True)
这个函数来把pcm转换为silk，但是感觉还是不太对的感觉（
坐等大佬们出解码器了
