### ISSUE TITLE
功能请求：QuickLogin

### ISSUE THREAD

**Issue by Zhou-Shilin** [chrononeko/bugtracker#45]
如题，希望QuickLogin能尽早完成开发。
![479DF7D8-E140-48F8-8700-6DB7371CBDB7](https://github.com/chrononeko/bugtracker/assets/86581525/0f756c0d-2dc4-4ef7-a1df-ded54e1e3f4b)

**Comment by ilharp** [comment]
该功能已在 [v0.0.50](https://github.com/chrononeko/chronocat/releases/tag/v0.0.50) 实装，v0.0.50 在 10 月 7 日就已发版。
