### ISSUE TITLE
发长文报错

### ISSUE THREAD

**Issue by jiangdengke** [chrononeko/bugtracker#48]
刚接触这个，想着先实现个复读机，使用http发然后报错。
发的内容:
2.指定container(容器)名称为mysql，并以3306端口访问，映射本机3306端口，可以根据自己的实际情况修改。并配置目录挂载。设置mysql密码为123456（可以根据自己的情况修改）。并且设置了重启策略。

2.1.此时，你的docker部署mysql已经完成了。下面进行开启远程访问权限。否则没法远程用数据库软件如Navicat进行远程连接。

docker exec -it mysql /bin/bash
3.进入mysql的container容器中。

mysql -uroot -p123456
4.使用步骤2设置的密码“123456”登录mysql。

ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '123456';

**Comment by ilharp** [comment]
> 然后报错

我甚至没有看到你的报错

**Comment by jiangdengke** [comment]
sorry，这是报错信息`500 internal server error`

**Comment by jiangdengke** [comment]
对不起，我的问题
