### ISSUE TITLE
Bug:发送tencent标准的silk语音时，好友私聊发送正常并可以播放，群组发送后PC端无法播放，手机端正常

### ISSUE THREAD

**Issue by qn8524king** [chrononeko/bugtracker#49]
前提：**语音是标准的tencent要求的silk语音类型，语音头已经正确转换为："\x02#!SILK_V3"的格式**

使用gocqhttp直接将silk以"cq=record"的形式发送至群组时是正常可以读取并播放的（电脑和安卓手机均可以正常发送并播放）
使用chrononeko发送时至群组时，电脑端显示为一张图片但无法点开，手机端正常显示为语音且可以正常播放

**Comment by ilharp** [comment]
Duplicate of #43

https://github.com/chrononeko/bugtracker/issues/43#issuecomment-1761626828

你使用的语音是旧版腾讯专属 Silk，现在发送语音需要使用新版专属 Silk。目前只有 Chronocat 的 [社区](https://chronocat.vercel.app/more/community) 提供了新版 Silk 的编码器。

**Comment by qn8524king** [comment]
> Duplicate of #43
> 
> [#43 (comment)](https://github.com/chrononeko/bugtracker/issues/43#issuecomment-1761626828)
> 
> 你使用的语音是旧版腾讯专属 Silk，现在发送语音需要使用新版专属 Silk。目前只有 Chronocat 的 [社区](https://chronocat.vercel.app/more/community) 提供了新版 Silk 的编码器。

使用了群里的编码器发送后，仍然是PC上普通QQ**（非NTQQ）**显示为图片，手机是正常的
![image](https://github.com/chrononeko/bugtracker/assets/49012015/d32b5154-bb36-4e7f-9b29-d8cb9c877c0f)
NTQQ是正常的
![image](https://github.com/chrononeko/bugtracker/assets/49012015/327b7c9f-d4a1-48b2-9c9c-8b75748d4158)

**Comment by ilharp** [comment]
非常抱歉，我误解了你的问题，你的问题和 #43 并不是相同的问题。

你的问题在于生成的音频文件需要以 `.amr` 作为后缀。使用其他结尾的后缀发送音频的话 PCQQ 无法识别。重命名一下音频文件就可以了。

再次抱歉。

**Comment by qn8524king** [comment]
> 非常抱歉，我误解了你的问题，你的问题和 #43 并不是相同的问题。
> 
> 你的问题在于生成的音频文件需要以 `.amr` 作为后缀。使用其他结尾的后缀发送音频的话 PCQQ 无法识别。重命名一下音频文件就可以了。
> 
> 再次抱歉。

可能不是跟改名有关？
因为我的代码是将音频从wav转换为pcm再转换为silk后，直接将silk文件的**二进制数据**传入Message.voice()内部进行发送的
（使用的是adapter_red）
目前看起来只是PC端普通版本的QQ存在显示为图片的问题

**Comment by ilharp** [comment]
看起来是 adapter-red 的实现有偏差。adapter-red 应当在上传语音文件的时候，专门在语音文件最后加上 `.amr` 后缀。由于此前我没有特意说过这件事，所以漏了这里的逻辑也很正常。

你可以带着这个 issue 前往 adapter-red 开一个新的 issue。

**Comment by qn8524king** [comment]
> 看起来是 adapter-red 的实现有偏差。adapter-red 应当在上传语音文件的时候，专门在语音文件最后加上 `.amr` 后缀。由于此前我没有特意说过这件事，所以漏了这里的逻辑也很正常。
> 
> 你可以带着这个 issue 前往 adapter-red 开一个新的 issue。

好的！了解了~
非常感谢您的回答！
