### ISSUE TITLE
功能请求：发送合并转发消息

### ISSUE THREAD

**Issue by ilharp** [chrononeko/bugtracker#5]
当前 Chronocat 不支持发送合并转发消息，希望支持此功能。

**Comment by Hieuzest** [comment]
it might be impossible to create fake messages previous impls

**Comment by MicroCBer** [comment]
> it might be impossible to create fake messages previous impls

AFAIK it could only be implemented in native side

**Comment by MicroCBer** [comment]
It's also not easy though, they used a ton of unknown structures rather than STL things. Also, there are pointer pointed to a pointer pointed to a pointer pointed to...., all with many messy offsets.

**Comment by MicroCBer** [comment]
I've approached sending the fake multi-message forward manually through native hooks, but I don't have enough time to make it practically usable in the production environment.

> All addresses below are related to wrapper.node+0x180000000, with QQNT 9.9.2-16183 x64.

It basically has these approaches:
- Difficulty: ***__ | Call `multiForwardMsgWithComment` ipc method with fake msgIds(note that the id is parsed as uint64 so strings won't work. using magic numbers like 114514 would be helpful). In native side, hook the SQL query function and return a fake message object when meeting the magic number. The SQL call functions are around 0x181fa6c07. We can pass the fake message object in the ipc method, and retrieve it by hooking multiForwardV8APIWrapper at 0x181fa6c07.
- Difficulty: ***** | Manually construct arguments and call 0x181fa6c07 uploadMultiForward. This is extremely difficult as there are so many virtual methods and reference counter(RC) pointers.
- Difficulty: **___ | Hook pullMForwardSubMsg(0x1815f2dd0) (the name is inaccurate; it the function calls uploadMultiForward; the sql query has been done before this function is called.) and replace parts of the message. It's the most feasible one. The second argument of the function is a linked list of messages to forward.
- Difficulty: ***__ | Manually call insert msg command to add the custom inexistent message into the db and call as usual.

Some information:

QQNT uses RC really heavily. Here's the (inaccurate and uncompleted) definition of memory span of it.
```c
struct Rc {
	int64_t unknown1;
	int64_t refCount;
	int16_t unknown2;
	void* pointer;
};
```
(The correction is not guaranteed for this, you'd better take a look at RC_USE(0x1812f4fe0) yourself, don't trust me :P)

QQNT loves virtual methods. All data can and only can (seemingly) be retrieved by virtual methods conveniently.

If there's nobody really hurry about this, we can wait until I have time to implement this. If there are, the info above can be used :)

cc @ilharp

**Comment by MicroCBer** [comment]
I've completed it. Everything's ready except the native layer monorepo to initialize. As I know nothing about monorepo, @ilharp

**Comment by MicroCBer** [comment]
Native part's ready now.
