### ISSUE TITLE
Bug: 部分表情获取错误

### ISSUE THREAD

**Issue by half-nothing** [chrononeko/bugtracker#56]
平台：
Windows 10 企业版

版本信息：
![image](https://github.com/chrononeko/bugtracker/assets/50048293/8b654afd-03c9-45fe-8a6c-b1bc02d54f16)
python：3.12.2
satori-python：0.11.1

详细报告：
![image](https://github.com/chrononeko/bugtracker/assets/50048293/9396fdac-d7c4-4d16-9030-3561df8cbad1)
![image](https://github.com/chrononeko/bugtracker/assets/50048293/fc92f45f-62cc-453d-a8f5-7c13b23c2207)
部分表情完全获取不到，但是却会触发事件

**Comment by ilharp** [comment]
已解决，可先下载 [这里](https://github.com/chrononeko/chronocat/actions/runs/8479619022) 的版本使用

**Comment by half-nothing** [comment]
ok，感谢大佬
