### ISSUE TITLE
Bug: 私聊消息参数错误

### ISSUE THREAD

**Issue by half-nothing** [chrononeko/bugtracker#57]
~~是的我又来了~~
平台：
Windows 10 企业版

版本信息：
![image](https://github.com/chrononeko/bugtracker/assets/50048293/8b654afd-03c9-45fe-8a6c-b1bc02d54f16)

详细报告：
![image](https://github.com/chrononeko/bugtracker/assets/50048293/5d04fee9-4a55-44fa-9603-f1f3e4bbe0c8)
`raw_message`
```json
{
  "op": 0,
  "body": {
    "id": 1812,
    "type": "message-created",
    "platform": "chronocat",
    "self_id": "123456",
    "timestamp": 1711807248000,
    "user": {
      "id": "123456",
      "avatar": "[http://thirdqq.qlogo.cn/headimg_dl?dst_uin=123456&spec=640"
    },
    "channel": {},
    "message": {
      "id": "7352156147280594561",
      "content": "ttt"
    }
  }
}
```
![image](https://github.com/chrononeko/bugtracker/assets/50048293/4e73904d-bfcf-4771-89bd-b310f1aa4723)
其中channel缺少字段
~~严谨一点的话这并不是缺少字段，因为根本没有字段~~
详见此[issue](https://github.com/RF-Tar-Railt/satori-python/issues/5)

**Comment by ilharp** [comment]
![image](https://github.com/chrononeko/bugtracker/assets/20179549/b633b4ad-115f-47c2-85e9-601eab7ee2a2)

正常好友关系下的聊天无此问题。

你的机器人和聊天的对方什么关系？你是否

1. 特别关注
1. 屏蔽
1. 拉黑
1. 忽略消息

了对方？

**Comment by half-nothing** [comment]
> ![image](https://private-user-images.githubusercontent.com/20179549/318200785-b633b4ad-115f-47c2-85e9-601eab7ee2a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDkwODgsIm5iZiI6MTcxMTgwODc4OCwicGF0aCI6Ii8yMDE3OTU0OS8zMTgyMDA3ODUtYjYzM2I0YWQtMTE1Zi00N2MyLTg1ZTktNjAxZWFiN2VlMmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE0MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMzAxNzJjZTgwNGJkNmY2ZTMwYWRiM2EyOTYyNTdhZWZlZGQwOTRkODUyMDIyNDFmMTZhNTdmY2ZiN2UwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hivE9u2LXVx-5bWigvTtBB7RRLDjd3gn9ro46XBsjpQ)
> 
> 正常好友关系下的聊天无此问题。
> 
> 你的机器人和聊天的对方什么关系？你是否
> 
> 1. 特别关注
> 2. 屏蔽
> 3. 拉黑
> 4. 忽略消息
> 
> 了对方？

是临时对话

**Comment by ilharp** [comment]
Chronocat 目前没有支持临时消息的计划。

**Comment by half-nothing** [comment]
彳亍
