### ISSUE TITLE
功能建议：同时监听ipv6地址

### ISSUE THREAD

**Issue by Cola-Ace** [chrononeko/bugtracker#64]
如题，在某些只有ipv6的机器上（一般场景为只有ipv6公网地址的家宽）外网无法通过ipv6访问chronocat，希望能在监听ipv4地址（0.0.0.0）的同时也监听ipv6地址（[::]）

**Comment by ilharp** [comment]
Chronocat 自 [2024-03-08 发布的 v0.2.2 版本](https://github.com/chrononeko/chronocat/releases/tag/v0.2.2) 开始支持 IPv6。由于 IPv6 各设备间默认不隔离，为了安全性考虑，配置中的 `listen` 字段默认为 `0.0.0.0`，即仅监听 IPv4（[配置参考](https://chronocat.vercel.app/guide/config/reference)）。要监听 IPv6，请将对应服务的 `listen` 字段手动改为 `[::]`。

如果遇到其他问题，请直接在下方回复。

**Comment by Cola-Ace** [comment]
已解决，感谢回复
