### ISSUE TITLE
错误码2159

### ISSUE THREAD

**Issue by Hun-Devil** [chrononeko/bugtracker#65]
在使用koishi的插件“@rinkuto/pixiv”时，输入插件相关指令就会报错
![f372fc2862fa882995410b431b2bcabc](https://github.com/chrononeko/bugtracker/assets/138664438/bbce0b57-45fc-42d3-b071-b5168676b2e3)

**Comment by ilharp** [comment]
[v0.2.15](https://github.com/chrononeko/chronocat/releases/tag/v0.2.15) 开始实现。
