### ISSUE TITLE
Bug: 在群名称过长时，接收群聊消息时会失去一部分群名称

### ISSUE THREAD

**Issue by liulyxandy-codemao** [chrononeko/bugtracker#74]
例：

> 群名称为`测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试`

<img width="853" alt="image" src="https://github.com/user-attachments/assets/f3dba8ca-1c08-47ee-920d-08be56cc10ed">

可见，发送群消息时群名称完好；接收群消息时则失去了后半部分的群名称。

> Chronocat版本：0.2.12
> engine-chronocat-api v0.2.12
> engine-chronocat-event v0.2.12

**Comment by ilharp** [comment]
确实存在此问题，预计在 v0.2.13 修复。
