### ISSUE TITLE
Bug: 打开小程序时会触发 Chronocat 启动

### ISSUE THREAD

**Issue by liulyxandy-codemao** [chrononeko/bugtracker#76]
https://github.com/user-attachments/assets/806dd8da-a8a9-444a-a6a3-4d5b09ac9144

如上视频，当在消息窗口打开一个小程序时，Chronocat 便会被触发并开始启动，且会卡在加载引擎。

**Comment by ilharp** [comment]
[最新 Action](https://github.com/chrononeko/chronocat/actions/runs/10139184889) 已修复，可以先下载使用；将会随 v0.2.16 发版。
