### ISSUE TITLE
功能请求：quote 消息

### ISSUE THREAD

**Issue by idanran** [chrononeko/bugtracker#8]
https://koishi.chat/zh-CN/api/message/elements.html#%E5%BC%95%E7%94%A8

**Comment by Hieuzest** [comment]
此功能在core上已经实现，只需相关适配器适配

**Comment by judgeou** [comment]
感觉不难，我直接进 `node_modules\@chronocat\koishi-plugin-adapter\lib\messager.js` 加了个 case 就行

```js
case 'quote': {
    this.children.push(red_1.r.reply(attrs['id'], attrs['id']))
}
```

**Comment by ilharp** [comment]
v0.0.55 支持了 quote 元素的收发，v0.0.66 添加了 quote 元素内的 author 信息、内容和转发支持。
