### ISSUE TITLE
使用Chronocat+satori时如何关闭自身上报功能？

### ISSUE THREAD

**Issue by vllbc** [chrononeko/bugtracker#81]
如何实现将机器人的发言不上报，即机器人的发言无法触发指令，否则如果设置COMMAND_START=["", "/"]，会有陷入死循环的风险，机器人不断触发自己的发言对应的指令，只能通过结束机器人来解决，请问该如何关闭自身上报功能？

**Comment by ilharp** [comment]
咨询得到了如下回复。根据建议，NoneBot 生态下应当寻找出现问题的对应插件，让插件自行解决死循环问题。

![](https://github.com/user-attachments/assets/45de638f-095b-4505-b4ff-ab60d8bb2b79)

由于此问题实际上是一个常见问题，因此在 issue 区置顶。有其他希望继续交流的情况的话可以继续回复此 issue。
