### ISSUE TITLE
功能请求: 支持以指定端口启动Chronocat

### ISSUE THREAD

**Issue by zhaomaoniu** [chrononeko/bugtracker#9]
避免多开 QQNT 时导致的端口占用错误

**Comment by ilharp** [comment]
Duplicate of #2

跟 #2 一块追踪吧。实现指定端口本身有以下要做的事情：

1. 设计配置文件的逻辑，选定文件格式，决定文件存放位置等等
1. 实现不同账号覆盖共有配置的逻辑，从而为某个账号单独指定配置（如端口号
